### ISSUE TITLE
test command::test_safe_command fails when running locally but seems to pass on GitHub

### ISSUE THREAD

**Issue by bast** [NordicHPC/sonar#119]
```
running 9 tests
test amd::test_find_block ... ok
test amd::test_extract_amd_information ... ok
test amd::test_parse_showpidgpus_command ... ok
test amd::test_parse_concise_command ... ok
test nvidia::test_parse_query_output ... ok
test nvidia::test_parse_pmon_output ... ok
test process::test_parse_ps_output ... ok
test batchless::test_batchless_jobs ... ok
test command::test_safe_command ... FAILED
```

```
---- command::test_safe_command stdout ----
thread 'command::test_safe_command' panicked at src/command.rs:203:13:
assertion failed: false
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: sonar::command::test_safe_command
             at ./src/command.rs:203:13
   4: sonar::command::test_safe_command::{{closure}}
             at ./src/command.rs:163:24
   5: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lars-t-hansen** [comment]
This test requires that target/debug/sonar exists, so if you're in a clean repo and you're just running `cargo test` I could see this failing.  Indeed, removing that file here and then running `cargo test` causes the same failure.

We could cat a different file, eg, src/main.rs, since that's unlikely to go away.
